# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-24 09:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerCertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u8bc1\u4e66\u540d\u79f0')),
                ('date', models.DateField(verbose_name='\u83b7\u5f97\u65f6\u95f4')),
            ],
        ),
        migrations.CreateModel(
            name='ComputerSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('software', models.TextField(verbose_name='\u719f\u7ec3\u64cd\u4f5c\u6216\u638c\u63e1\u70b9\u8f6f\u4ef6')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromdate', models.DateField(verbose_name='\u8d77\u59cb\u65f6\u95f4')),
                ('todate', models.DateField(verbose_name='\u7ed3\u675f\u65f6\u95f4')),
                ('college', models.CharField(max_length=20, verbose_name='\u7cfb\u522b/\u5b66\u9662')),
                ('schooltype', models.ImageField(choices=[(1, 'fulltime'), (2, 'parttime'), (3, '\u81ea\u8003'), (4, '\u6210\u4eba\u6559\u80b2')], upload_to=b'', verbose_name='\u5b66\u4e60\u5f62\u5f0f')),
                ('major', models.CharField(max_length=20, verbose_name='\u4e13\u4e1a')),
                ('degree', models.IntegerField(choices=[(1, '\u7814\u7a76\u751f\uff08\u7855\u58eb\uff09'), (2, '\u672c\u79d1\uff08\u5b66\u58eb\uff09'), (3, '\u5927\u4e13\uff08\u65e0\u5b66\u4f4d\uff09')], verbose_name='\u5b66\u5386/\u5b66\u4f4d')),
                ('average', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='\u5e73\u5747\u5206')),
                ('gpa', models.CharField(max_length=10, verbose_name='GPA')),
            ],
        ),
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobby', models.CharField(max_length=10, verbose_name='\u5174\u8da3\u7231\u597d')),
            ],
        ),
        migrations.CreateModel(
            name='Honor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='\u65e5\u671f')),
                ('title', models.CharField(max_length=10, verbose_name='\u540d\u79f0')),
            ],
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='\u65e5\u671f')),
                ('place', models.CharField(max_length=20, verbose_name='\u5b9e\u4e60\u5355\u4f4d')),
                ('department', models.CharField(max_length=20, verbose_name='\u5b9e\u4e60\u90e8\u95e8')),
                ('work', models.TextField(verbose_name='\u5de5\u4f5c\u5185\u5bb9')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u51fa\u7248\u7269\u540d\u79f0')),
                ('date', models.DateField(verbose_name='\u51fa\u7248\u65f6\u95f4')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='\u65e5\u671f')),
                ('place', models.CharField(max_length=20, verbose_name='\u7814\u7a76\u5355\u4f4d')),
                ('work', models.TextField(verbose_name='\u7814\u7a76\u5185\u5bb9')),
            ],
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='\u65e5\u671f')),
                ('title', models.CharField(max_length=10, verbose_name='\u540d\u79f0')),
            ],
        ),
        migrations.CreateModel(
            name='SocialActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='\u65e5\u671f')),
                ('description', models.TextField(verbose_name='\u6d3b\u52a8/\u5de5\u4f5c')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialAward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u5956\u52b1\u540d\u79f0')),
                ('date', models.DateField(verbose_name='\u83b7\u5956\u65e5\u671f')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20, verbose_name='\u59d3\u540d')),
                ('gender', models.CharField(choices=[('M', '\u7537'), ('F', '\u5973')], max_length=1, verbose_name='\u6027\u522b')),
                ('birthday', models.DateField(verbose_name='\u51fa\u751f\u65e5\u671f')),
                ('marriage', models.CharField(choices=[('Y', '\u5df2\u5a5a'), ('N', '\u672a\u5a5a')], max_length=1, verbose_name='\u5a5a\u59fb\u72b6\u51b5')),
                ('birthland', models.CharField(max_length=30, verbose_name='\u51fa\u751f\u5730')),
                ('nationality', models.CharField(max_length=30, verbose_name='\u56fd\u7c4d')),
                ('address', models.CharField(max_length=50, verbose_name='\u5bb6\u5ead\u4f4f\u5740')),
                ('postcode', models.CharField(max_length=10, verbose_name='\u90ae\u653f\u7f16\u7801')),
                ('email', models.EmailField(max_length=254, verbose_name='\u7535\u5b50\u90ae\u7bb1')),
                ('phone', models.CharField(max_length=20, verbose_name='\u7535\u8bdd\u53f7\u7801')),
                ('passport', models.CharField(max_length=10, verbose_name='\u62a4\u7167\u53f7\u7801')),
                ('target', models.IntegerField(choices=[(1, '\u672c\u79d1'), (2, '\u7855\u58eb'), (3, '\u535a\u58eb')], verbose_name='\u7533\u8bf7\u76ee\u6807')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Voluntary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='\u6d3b\u52a8\u65e5\u671f')),
                ('activity', models.TextField(verbose_name='\u6d3b\u52a8\u5185\u5bb9')),
                ('result', models.TextField(verbose_name='\u6d3b\u52a8\u6210\u679c')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
        ),
        migrations.AddField(
            model_name='specialaward',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student'),
        ),
        migrations.AddField(
            model_name='socialactivity',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student'),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student'),
        ),
        migrations.AddField(
            model_name='researchexperience',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student'),
        ),
        migrations.AddField(
            model_name='publication',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student'),
        ),
        migrations.AddField(
            model_name='internship',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student'),
        ),
        migrations.AddField(
            model_name='honor',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student'),
        ),
        migrations.AddField(
            model_name='hobby',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student'),
        ),
        migrations.AddField(
            model_name='education',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student'),
        ),
        migrations.AddField(
            model_name='computerskill',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student'),
        ),
        migrations.AddField(
            model_name='computercertificate',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student'),
        ),
    ]
